### ISSUE TITLE
FatalError: Unparenthesized `a ? b : c ? d : e` is not supported

### ISSUE THREAD

**Issue by manavo** [ringcentral/ringcentral-php#103]
Just upgraded to the latest version and I'm getting this error:

```
Symfony\Component\ErrorHandler\Error\FatalError: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`
  File "/vendor/ringcentral/ringcentral-php/src/Platform/Platform.php", line 201
```

I'll try and get a PR submitted, but for now just trying to revert to the previous version since this breaks things completely!

**Comment by jvrsolis** [comment]
any update on merging this in?

**Comment by coxlr** [comment]
Looks like this issue was introduced in v2.3.0 from #100 I was able to work around the issue short term by using v2.2.5
