### ISSUE TITLE
PHP SDK issue

### ISSUE THREAD

**Issue by adarshu** [ringcentral/ringcentral-php#11]
Hard to know what SDK version to use for composer. I used 0.5.0 and it worked. >= 1.0.0 didn't work.

**Comment by kirill-konshin** [comment]
The interface of classes has changed in 1.0. Can you describe your issue?

**Comment by adarshu** [comment]
Using "1.0.0" fails in "compose update" command. Only "0.5.0" worked, wanted to point that out. I noticed this issue while hacking with your API at Integrate 2015 hackathon.

**Comment by kirill-konshin** [comment]
You need to have 

```json
{
  "minimum-stability": "dev"
}
```

in your `composer.json`.
