### ISSUE TITLE
Conflict with other packages because "guzzlehttp/psr7": "dev-master" is required

### ISSUE THREAD

**Issue by austin881** [ringcentral/ringcentral-php#12]
Looking into implementing RingCentral into our app I have hit a conflict.

[ringcentral/ringcentral-php](https://packagist.org/packages/ringcentral/ringcentral-php) requires `guzzlehttp/psr7: dev-master`
However, another dependency for our project, [intervention/image](https://packagist.org/packages/intervention/image), requires `guzzlehttp/psr7: ~1.1`
So when doing a composer require for the dev-master it fails as it complains that `intervention/image` needs 1.1.

```
Austins-MacBook-Air:laravel austin$ composer require ringcentral/ringcentral-php
Using version dev-master for ringcentral/ringcentral-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: guzzlehttp/psr7[dev-master, 1.2.0].
    - Can only install one of: guzzlehttp/psr7[dev-master, 1.2.0].
    - Can only install one of: guzzlehttp/psr7[dev-master, 1.2.0].
    - ringcentral/ringcentral-php dev-master requires guzzlehttp/psr7 dev-master -> satisfiable by guzzlehttp/psr7[dev-master].
    - Installation request for ringcentral/ringcentral-php dev-master -> satisfiable by ringcentral/ringcentral-php[dev-master].
    - Installation request for guzzlehttp/psr7 == 1.2.0.0 -> satisfiable by guzzlehttp/psr7[1.2.0].

Installation failed, reverting ./composer.json to its original content.
```

Do you have a good reason for requiring `"guzzlehttp/psr7": "dev-master"`? Can you please change the composer.json *require* dependency?

**Comment by kirill-konshin** [comment]
We use a PHP 5.3 compatible fork of `guzzlehttp/psr7`. I will look into how we can fix this.

**Comment by kirill-konshin** [comment]
I've pushed version 1.1.0 which has the conflict resolved.
