### ISSUE TITLE
3-Legged OAuth in PHP SDK

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-php#22]
Reported by customer in [RingCentral Developer Community](https://devcommunity.ringcentral.com/ringcentraldev/topics/creating-request-to-activate-3-legged-authorization):

I am having issue when using PHP for 3-Legged.
When I click on Authorize button on login consent screen, I am receiving following error:

> Authentication code cannot be obtained successfully for the given mailbox.

![php-sdk-threeleggedoauth-issue](https://cloud.githubusercontent.com/assets/2376876/13259289/934c4612-da0b-11e5-95f5-6812e7d63655.png)

Knowing that a developer must make a call to `/restapi/oauth/authorize` with a query string that contains key/values for: `redirect_uri, client_id, state, response_type, and prompt` leads me to `grep -lr "/authorize ./" from root of the SDK without results for 3-Legged Auth using the appropriate route.

Since PHP is a server-side language, that leads me to think that a PHP developer implementing 3-Legged OAuth is required to use either our [https://github.com/ringcentral/ringcentral-js](JS SDK) in the client-side code or implement their own code, to generate the server-client requests to apply appropriate data and handle client-side redirects appropriately.

**Comment by M-Shahbaz** [comment]
using devtest account:
in network response showing: 
`{"status":{"success":false,"code":716,"message":"Authentication code cannot be obtained successfully for the given mailbox.","fields":null,"errorCode":"LOGIN_API_GET_AUTHENTICATION_CODE_FAIL"},"sessionid":"SESSION_IDxxxxx","result":"","spent":110}`

Authorize URL for 3-Legged OAuth:

`https://platform.devtest.ringcentral.com/restapi/oauth/authorize?client_id=APP- KEY&response_type=code&redirect_uri=URL-ENCODE-RIDIRECT-URI&prompt=login+consent&state=RANDOM-STATE-NUMBER`

On server side Node.js is not available only PHP (LAMP)

I tried using Browser JS SDK, and having exactly same issue that is:

> Authentication code cannot be obtained successfully for the given mailbox.

 
. (May be something with this account?), Although I can get access token using username and password (2-legged OAuth) of same account but require 3-legged OAuth

```
	<script type="text/javascript" src="build/promise.js"></script>
	<script type="text/javascript" src="build/fetch.js"></script>
	<script type="text/javascript" src="build/pubnub.js"></script>
	<script type="text/javascript" src="build/ringcentral.js"></script><!-- or ringcentral.min.js -->
	<script type="text/javascript">

		var sdk = new RingCentral.SDK({
					server: 'https://platform.devtest.ringcentral.com', // SANDBOX
					//server: 'https://platform.ringcentral.com', // PRODUCTION
					appKey: 'APP KEY'
					});
		var platform = sdk.platform();
		
		var authorizeURI = platform.authUrl({
			redirectUri: 'REDIRECT URI',
			prompt: 'login consent',
			state: 'RANDOM STATE'
		});
		// Open browser to authorizeURI (which should contain all the properly formatted queryString parameters in place)
		window.open(authorizeURI, '_self', '');
	</script>
```

**Comment by grokify** [comment]
The error encountered can result due to TLS 1.2 enforcement on our server. Check your client to verify it supports TLS 1.2.

I've reformatted it below for easier reading.

```
{
    "status":{
        "success":false,
        "code":716,
        "message":"Authentication code cannot be obtained successfully for the given mailbox.",
        "fields":null,
        "errorCode":"LOGIN_API_GET_AUTHENTICATION_CODE_FAIL"
    },
    "sessionid":"SESSION_IDxxxxx",
    "result":"",
    "spent":110
}
```

I'm closing this due to the age of this issue. Feel free to post if this is still an issue.
