### ISSUE TITLE
For what is the comment for true false usage in the login example of README used?

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-php#26]
In the [README.md](README.md) file, for the login example below, there is a comment about using `true` or `false`, what is that for exactly (or is this outdated and needs to be modified)?

Here is documentation in question:

```
$sdk->platform()->login('username', 'extension (or leave blank)', 'password'); // change true to false to not remember user
```

**Comment by kirill-konshin** [comment]
Comment is outdated...
