### ISSUE TITLE
Authorization header is not specified

### ISSUE THREAD

**Issue by janevoo** [ringcentral/ringcentral-php#28]
Guys, few days ago I started to receive this error:

`Exception: Authorization header is not specified
SDK HTTP Error at https://platform.ringcentral.com/restapi/v1.0/account/~/extension/~/message-store?messageType=VoiceMail&dateFrom=2016-04-16T07%3A00%3A02%2B03%3A00&dateTo=2016-04-17T20%3A55%3A15%2B03%3A00
Response text: {
  "errorCode" : "OAU-123",
  "message" : "Authorization header is not specified",
  "errors" : [ {
    "errorCode" : "OAU-123",
    "message" : "Authorization header is not specified"
  } ]
}
Previous: Response has unsuccessful status`

Reproduced only on production server (works fine on devtest) at each api call except authorization. Can you help me please? Is it server-side bug?

**Comment by grokify** [comment]
@janevoo We are looking into this issue and will follow up when we have an update. It appears to be a backend, server-side issue at this time.

**Comment by janevoo** [comment]
Thanks. Waiting for any updates.

**Comment by grokify** [comment]
@janevoo We have tested the system and it should be operational again. Please try it out.

**Comment by janevoo** [comment]
@grokify still reproduced =(

**Comment by grokify** [comment]
@janevoo Can you check again? It seems to be up for other developers that reported this issue. You can see there responses on the community: https://devcommunity.ringcentral.com/ringcentraldev/topics/is-ringcentral-api-getsubscription-presence-down. Thanks.

**Comment by janevoo** [comment]
@grokify thanks! Totally working now.
