### ISSUE TITLE
Unauthorized for this grant type

### ISSUE THREAD

**Issue by manojdhiman** [ringcentral/ringcentral-php#30]
The api is throwing me the error . `{ "error" : "unauthorized_client", "error_description" : "Unauthorized for this grant type" }` on authData.php page while i am trying to login .

**Comment by anilkumarbp** [comment]
Hi @manojdhiman , 

Please take a look at our `PHP Demo` using the `OAuth 2.0` feature here : 
https://github.com/grokify/ringcentral-demos-oauth/tree/master/php 

Kindly follow the instructions listed in the [README.md](https://github.com/grokify/ringcentral-demos-oauth/blob/master/php/README.md)
