### ISSUE TITLE
Problem in sending Fax?

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-php#37]
Hi
I run the demo/fax.php

always return 

Response text: {
  "message" : "Bad Request",
  "errors" : [ ]
}
Previous: Response has unsuccessful status
any idea why ?

**Comment by anilkumarbp** [comment]
Hi @mgw2007,

Have you followed our `demo` instructions within the SDK : [How to Demo](https://github.com/ringcentral/ringcentral-php#how-to-demo)

If you have, could you provide us the HTTP request and the Response Headers to investigate more ?

**Comment by mgw2007** [comment]
Hi @anilkumarbp  

I flow the instructions within the SDK : How to Demo
and the login part working fine

the problem in this part

$request = $rcsdk->createMultipartBuilder()
                 ->setBody(array(
                     'to'         => array(
                         array('phoneNumber' => $credentials['username']),
                     ),
                     'faxResolution' => 'High',
                 ))
                 ->add('Plain Text', 'file.txt')
                 ->add(fopen('https://developers.ringcentral.com/assets/images/ico_case_crm.png', 'r'))
                 ->request('/account/~/extension/~/fax');
$response = $platform->sendRequest($request);


this the is the Rsponse


 ============START==================== 
HTTP/1.1 400 Bad Request
Server: nginx/1.8.0
Date: Thu, 14 Jul 2016 21:25:50 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 49
Connection: keep-alive
Set-Cookie: RCRoutingInfo=B:JjvG963zMhLp2i9ovcWFNFBA3Z0SlO9Db3kZ8SMmxroqJmbYi/T15GSgF4kFzfRE; Path=/
RCRequestId: 89be37a4-4a09-11e6-b36a-005056bb594d
RoutingKey: SJC11P01PAS01
X-LoadMetric: 4
X-Rate-Limit-Group: heavy
X-Rate-Limit-Limit: 10
X-Rate-Limit-Remaining: 9
X-Rate-Limit-Window: 60
Content-Language: en-US
X-AGW-Host: sjc11-c01-agw02.devtest.ringcentral.com

{
  "message" : "Bad Request",
  "errors" : [ ]
}
 ============END====================

**Comment by anilkumarbp** [comment]
You are required to import the `namespace` (or `class`) to the current scope. Please make sure to include below into your file : ( file being used to demo Login and fax ) 

```
use RingCentral\SDK\Http\HttpException;
use RingCentral\http\Response;
```

This should fix your problem. Kindly confirm.

**Comment by mgw2007** [comment]
Solved thank you Anil
