### ISSUE TITLE
How to fix error: Phone number doesn't belong to extension

### ISSUE THREAD

**Issue by numanilyas** [ringcentral/ringcentral-php#38]
Hi,
I am using this SDK to send messages. My app works fine on sandbox but on production I am having error "Phone number doesn't belong to extension". Please let me know how to setup my number to send SMS.

Regards,
Numan Ilyas

**Comment by anilkumarbp** [comment]
Hi @numanilyas . Please make sure the `phoneNumbers` used to send `SMS` follow the `E.164` format. 

If you have any concerns still, please open a support case at `devsupport@ringcentral.com` and one of our team members would reply to the case.

**Comment by grokify** [comment]
To verify the phone number being used is associated with the extension, call the extensions `phone-number` endpoint, e.g. `account/~/extension/~/phone-number` and ensure the phone number being used is returned. It should also have the `feature` called `SmsSender` present.

You can see this in our Developer Guide here:

* [API Developer Guide](http://developing-with-ringcentral.readthedocs.io/en/latest/account_extension/#phone-numbers)
* [Ruby SDK Docs](http://ringcentral-sdk-ruby.readthedocs.io/en/latest/usage/messages/SMS-Messages/#retrieving-a-list-of-valid-sms-sending-numbers)

**Comment by numanilyas** [comment]
Thanks John and Anil. I will open case with devsupport@ringcentral.com.

**Comment by anilkumarbp** [comment]
Happy to help you @numanilyas . Closing this issue for now.
