### ISSUE TITLE
Documentation incorrect for "Authentication lifecycle"

### ISSUE THREAD

**Issue by raffLHS** [ringcentral/ringcentral-php#46]
The following is incorrect:

$sdk->platform()->auth->setData(json_decode(file_get_contents($file));

The following works:

$sdk->platform()->auth()->setData((array) json_decode(file_get_contents($file)));

**Comment by kirill-konshin** [comment]
Thanks for reporting!

It should be just `json_decode(file_get_contents($file), true)`. Adding `true` as second parameter of `json_decode` returns an array. But despite of that a plain object is also acceptable bc PHP can access it's properties as array keys too. In demo it was used in a right way.
