### ISSUE TITLE
Error when run composer.phar command

### ISSUE THREAD

**Issue by oepl** [ringcentral/ringcentral-php#54]
I am installing SDK in local machine – Downloaded ZIP file and extract in Desktop.

Go to terminal (Using Ubuntu 17.04) and follow below steps

**Step 1 ::  curl -sS https://getcomposer.org/installer | php**
Run successfully

**Step 2 :: php composer.phar require ringcentral/ringcentral-php**

**Getting below error – Will you help me to resolve?** 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package ringcentral/ringcentral-php No version set (parsed as 1.0.0) is satisfiable by ringcentral/ringcentral-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by kirill-konshin** [comment]
If you’re installing via composer you don’t need a zip file. Just require via composer in your project.

**Comment by oepl** [comment]
Can you please explain me how to do? I tried so many ways and try to find in Google as well but did not found any help. Composer is installed in my Ubuntu machine.

**Comment by anilkumarbp** [comment]
Below are some of the ways in which you can add `ringcentral-php` as a package to your project:
**assuming you have Composer installed

1.) Create a `composer.json` :
Go to your project folder. Create a `composer.json` and `require` the package as shown below:
```
{
    "require": {
        "ringcentral/ringcentral-php": "^2.1"
    }
}
```
To know more on how to create a `composer.json`, go on to read this: 
https://getcomposer.org/doc/01-basic-usage.md#composer-json-project-setup

2.) Directly `require` the package :
Go to your project folder. Open Terminal and type:
`composer require ringcentral/ringcentral-php`

**Comment by oepl** [comment]
I have added below line in comoser.json and run your step 2 command but it does not work. I have downloaded  "ringcentral-php-2.1.2.zip"

Screen shot : https://s.nimbus.everhelper.me/share/1299276/piyff1vwfbmfvi14n2rn

**Comment by oepl** [comment]
I have to use this SDK for SuiteCRM application so I am creating vendor folder in desktop first and then after i will use SDK in my CRM application.
