### ISSUE TITLE
Update App Key and App Secret terminology to Client ID and Client Secret

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-php#55]
The terminology in the Developer Portal has changed from App Key and App Secret to Client ID and Client Secret to better align with the OAuth 2.0 standard (IETF RFC 6749). There have been some questions on where to get the App Key and App Secret now that these terms are no longer used. Please update to reflect this.

**Comment by kirill-konshin** [comment]
PR is welcome.

**Comment by kirill-konshin** [comment]
Fixed
