### ISSUE TITLE
Get attachment

### ISSUE THREAD

**Issue by oepl** [ringcentral/ringcentral-php#57]
Could you help me to use SDK for get attachment code? I am using below but do not know hot to get binary data. HTTP status 200 Ok.

$response = $this->platform->get('/account/~/extension/~/message-store/' . $messageId . '/content/' . $attachmentId)
                                    ->multipart();
        
        return $response->json();

**Comment by kirill-konshin** [comment]
It is neither `multipart` nor `json`. Use `raw()` method to get a body stream http://docs.guzzlephp.org/en/stable/psr7.html#id2

**Comment by oepl** [comment]
Thank you
