### ISSUE TITLE
When trying to subscribe to push notification: Call to a member function register() on null

### ISSUE THREAD

**Issue by thesubhendu** [ringcentral/ringcentral-php#58]

**Comment by thesubhendu** [comment]
I tried with example request given in documentation. 
```
$subscription = $sdk->createSubscription()
                     ->addEvents(array('/restapi/v1.0/account/~/extension/~/presence'))
                     ->addListener(Subscription::EVENT_NOTIFICATION, function (NotificationEvent $e) {
                
                         print_r($e->getPayload());
             });
                    
$apiResponse = $subscription->register();
```
And I got null response when trying to dump $subscription variable.

**Comment by anilkumarbp** [comment]
@thesubhendu ,
Can you try creating a subscription as shown in the Demo below: 
https://github.com/ringcentral/ringcentral-php/blob/master/demo/subscription.php

**Comment by kirill-konshin** [comment]
There was a bug in documentation, per `EventDispatcher` interface `addListener ` can't be chained.
