### ISSUE TITLE
Docs indicate PHP 5.5+ support but dependency requires PHP 7.0

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-php#61]
Reported on the DevCommunity using PHP 5.6.23:

https://devcommunity.ringcentral.com/ringcentraldev/topics/sms-api-for-sending-text-to-customers-and-get-reply-against-sms

These installation instructions with PHP 5.6.23 results in the error below:

```bash
$ curl -sS https://getcomposer.org/installer | php
$ php composer.phar require ringcentral/ringcentral-php
```
Error:
```
  Problem 1
    - phpunit/php-token-stream 2.0.1 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - phpunit/php-token-stream 2.0.1 requires php ^7.0 -> your PHP version (5.6.23) does not satisfy that requirement.
    - Installation request for phpunit/php-token-stream (locked at 2.0.1) -> satisfiable by phpunit/php-token-stream[2.0.1]
```

**Comment by vyshakhbabji** [comment]
@grokify I just installed curl on Mac using  -- > 
$brew install curl


$curl -sS https://getcomposer.org/installer | php

**Comment by vyshakhbabji** [comment]
Not reproducible. Please reopen the issue if necessary.

**Comment by wonderboyjon** [comment]
I was able to reproduce this issue. The current composer.lock file for this repo specifies that that package phpunit/php-token-stream 2.0.1 should be installed, which does indeed require PHP 7.0. I was able to run a composer update on this repo to regenerate the lock file and ended up with a "valid" version of this library being specified instead.
