### ISSUE TITLE
Incomplete/incorrect function documentation

### ISSUE THREAD

**Issue by wonderboyjon** [ringcentral/ringcentral-php#63]
Some of the function descriptions in this library are incomplete, incorrect or missing entirely, particularly within `Platform.php`

For example:

`/**
     * @param string $options['redirectUri']
     * @param string $options['state']
     * @param string $options['brandId']
     * @param string $options['display']
     * @param string $options['prompt']
     * @param array  $options
     * @throws ApiException
     * @return ApiResponse
     */
    public function authUrl($options)
    {

        return $this->createUrl(self::AUTHORIZE_ENDPOINT . '?' . http_build_query(
            array (
            'response_type' => 'code',
            'redirect_uri'  => $options['redirectUri'] ? $options['redirectUri'] : null,
            'client_id'     => $this->_clientId,
            'state'         => $options['state'] ? $options['state'] : null,
            'brand_id'      => $options['brandId'] ? $options['brandId'] : null,
            'display'       => $options['display'] ? $options['display'] : null,
            'prompt'        => $options['prompt'] ? $options['prompt'] : null
        )), array(
            'addServer'     => 'true'
        ));
    }`
This function does not return an `ApiResponse` object, it returns a string.
This function does not throw an `ApiException`.
There is no description of what this function actually does/what it's for.

`public function auth()
    {
        return $this->_auth;
    }`

This function does not have any kind of description or specify what the return type is.

There are numerous other examples of this issue. It makes it very difficult to know whether we're actually using the functions correctly and causes a nightmare for the IDE when it tries to detect issues such as uncaught exceptions or mismatched return types.

Is there any chance someone could go through and fix/add/tidy up the function descriptions please?

**Comment by kirill-konshin** [comment]
Sure, we can update all the descriptions.

> There are numerous other examples of this issue

Please make a list of things that has to be fixed, this will help to fix the issue in a timely manor. PR is also appreciated.

**Comment by wonderboyjon** [comment]
I'll see what I can put together when I get some time. Though even if I am able to make a PR, I'm unlikely to be able to add proper function descriptions to each function, since I wasn't the one that wrote them and I do not necessarily know what their intended purposes/use cases are (I literally started trying to use this library for the first time yesterday when I encountered these issues).

Ideally the function creators or someone with greater familiarity with their usages would be responsible for creating those descriptions.

**Comment by kirill-konshin** [comment]
Closed via #64
