### ISSUE TITLE
Code searching for /../vendor/autoload.php

### ISSUE THREAD

**Issue by surefooted** [ringcentral/ringcentral-php#65]
Hello, 
I have followed the installation instructions and installed the ringcentral php code in a folder on our website. On trying to run the demo file I get the following error in the error log:
[04-Apr-2018 12:33:58 America/Denver] PHP Fatal error:  require_once(): Failed opening required '/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /site-home/site-name/public_html/iupgrade/ringcentral/vendor/ringcentral/ringcentral-php/demo/_bootstrap.php on line 3
I am attaching the directory structure of the files installed. 
![directory-structure](https://user-images.githubusercontent.com/30171431/38353859-66e005ca-38d5-11e8-947c-fd3b305d270a.jpg)

Thanks!

**Comment by kirill-konshin** [comment]
Are you trying to launch the demo from composer folder, when package was installed using composer? If yes, the demo should be used as a standalone app, clone the repository, install dependencies and run it.

**Comment by surefooted** [comment]
Thanks kirill-konshin, I tried your suggestion and the directory structure looks the following:
![ringcentral dir](https://user-images.githubusercontent.com/30171431/38408750-7d62faa6-399c-11e8-98b4-7377fdd0b591.png)

But I am still getting the error [06-Apr-2018 07:35:30 UTC] PHP Fatal error:  Class 'RingCentral\SDK\SDK' not found in /site-home/site-name/public_html/iupgrade/ringcentral/demo/authData.php on line 14

How to resolve this?
Thanks!
