### ISSUE TITLE
Laravel 5.6 incompatibility with symfony/event-dispatcher

### ISSUE THREAD

**Issue by mastrip2** [ringcentral/ringcentral-php#71]
When installing ringcentral to a fresh install of laravel 5.6 you get a error message telling you it cant because it requires symfony/event-dispatcher ^2.7|^3.3.2. Laravel currently uses symfony/event-dispatcher 4.0.10. Is it possible to bring support up for this version? #19

**Comment by kirill-konshin** [comment]
PR is welcome :)

**Comment by webpro125** [comment]
I have same problem. :(

**Comment by shopapps** [comment]
I'm also seeing this error when trying to update a project to Laravel 5.6

Not sure how to create a PR but is it as simple as adjusted line 39 of composer.json to read:

    "symfony/event-dispatcher": "^2.7|^3.3.2|^4.0",

(excuse my ignorance if the above is totally incorrect) :-)

**Comment by mastrip2** [comment]
I believe so.

**Comment by shopapps** [comment]
I forked the project edited the file and all installed ok. 👍

**Comment by kirill-konshin** [comment]
Make a PR please

**Comment by shopapps** [comment]
will google how to do that later if i get time (git newbie) :-)
