### ISSUE TITLE
Yii2 installation error with symfony/event-dispatcher v4.1.6

### ISSUE THREAD

**Issue by AndreyBCC** [ringcentral/ringcentral-php#77]
Hi! 
When I tried to install ringcentral-php in Yii2 project by using composer I got this error : Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install ringcentral/ringcentral-php 2.1.3
    - Conclusion: don't install ringcentral/ringcentral-php 2.1.2
    - Conclusion: remove symfony/event-dispatcher v4.1.6
    - Installation request for ringcentral/ringcentral-php ^2.1 -> satisfiable by ringcentral/ringcentral-php[2.1.1, 2.1.2, 2.1.3].
    - Conclusion: don't install symfony/event-dispatcher v4.1.6
    - ringcentral/ringcentral-php 2.1.1 requires symfony/event-dispatcher ^2.7|^3.3.2 -> satisfiable by symfony/event-dispatcher[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21,
v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.40, v2.7.41, v2.7.42, v2.7.43, v2.7.44, v2.7.45, v2.7.46, v2.7.47, v2.7.48, v2
.7.49, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2
.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.42, v2.8.43, v2.8.44, v2.8.45, v2.8.46, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16,
 v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/event-dispatcher[v2.7.0, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.1, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.10, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.11, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.12, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.13, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.14, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.15, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.16, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.17, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.18, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.19, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.2, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.20, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.21, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.22, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.23, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.24, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.25, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.26, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.27, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.28, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.29, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.3, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.30, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.31, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.32, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.33, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.34, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.35, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.36, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.37, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.38, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.39, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.4, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.40, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.41, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.42, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.43, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.44, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.45, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.46, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.47, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.48, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.49, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.5, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.6, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.7, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.8, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.7.9, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.0, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.1, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.10, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.11, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.12, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.13, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.14, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.15, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.16, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.17, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.18, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.19, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.2, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.20, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.21, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.22, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.23, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.24, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.25, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.26, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.27, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.28, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.29, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.3, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.30, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.31, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.32, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.33, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.34, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.35, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.36, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.37, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.38, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.39, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.4, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.40, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.41, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.42, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.43, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.44, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.45, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.46, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.5, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.6, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.7, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.8, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v2.8.9, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.10, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.11, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.12, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.13, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.14, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.15, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.16, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.17, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.18, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.2, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.3, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.4, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.5, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.6, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.7, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.8, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.3.9, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.0, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.1, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.10, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.11, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.12, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.13, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.14, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.15, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.16, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.17, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.2, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.3, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.4, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.5, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.6, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.7, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.8, v4.1.6].
    - Can only install one of: symfony/event-dispatcher[v3.4.9, v4.1.6].
    - Installation request for symfony/event-dispatcher (locked at v4.1.6) -> satisfiable by symfony/event-dispatcher[v4.1.6].

Installation failed, reverting ./composer.json to its original content.

Can any body tell how can I workaround this error?

Thank's.

**Comment by kirill-konshin** [comment]
@vyshakhbabji please take a look, this is probably fixed by now.
