### ISSUE TITLE
Seem to never be able to authorize... what could I be doing wrong?

### ISSUE THREAD

**Issue by mayokingcomics** [ringcentral/ringcentral-php#8]
Do I need to use sandbox accounts in the "devtest" area? I would be happy with just rest API GEt's .... but I would like to get this working 

xception: Refresh token has expired Exception: Bad Application Release Status: Blocked SDK HTTP Error: Bad Application Release Status: Blocked at https://platform.devtest.ringcentral.com/restapi/oauth/token stdClass Object ( [error] => invalid_client [error_description] => Bad Application Release Status: Blocked ) Previous: Response has unsuccessful status #0 /home/dashboardrmonnet/public_html/test/rc/lib/platform/Platform.php(238): RingCentral\http\Request->send() #1 /home/dashboardrmonnet/public_html/test/rc/lib/platform/Platform.php(145): RingCentral\platform\Platform->authCall(Object(RingCentral\http\Request)) #2 /home/dashboardrmonnet/public_html/test/rc/demo/authData.php(43): RingCentral\platform\Platform->authorize('xxxxx', 'xxxxxxx', 'xxxxxxxx', true) #3 /home/dashboardrmonnet/public_html/test/rc/index.php(3): require('/home/dashboard...') #4 {main}

**Comment by kirill-konshin** [comment]
You need to use sandbox credentials with devtest URLs, that's correct. What version of SDK do you use?

Best regards
Kirill Konshin
