### ISSUE TITLE
Composer error: incompatible with guzzlehttp/psr7 2.x+

### ISSUE THREAD

**Issue by CitizenBeta** [ringcentral/ringcentral-php#98]
Here's the error I'm getting from composer when trying to use this package with Laravel 8 on PHP 8:

> Problem 1
>     - ringcentral/ringcentral-php[2.2.0, ..., 2.2.5] require guzzlehttp/psr7 ^1.4.2 -> found guzzlehttp/psr7[1.4.2, ..., 1.x-dev] but the package is fixed to 2.1.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
>     - Root composer.json requires ringcentral/ringcentral-php ^2.2 -> satisfiable by ringcentral/ringcentral-php[2.2.0, ..., 2.2.5].
> 

Any help would be greatly appreciated.

**Comment by tylerlong** [comment]
I think it is time to update all dependencies to latest version: https://github.com/ringcentral/ringcentral-php/blob/master/composer.json#L13-L21

**Comment by CitizenBeta** [comment]
Thanks! What's next to get this merged in?

**Comment by tylerlong** [comment]
I merged it, but I don't have the permission to release a new version to Composer.
I think you could require it from GitHub directly: https://www.daggerhartlab.com/composer-how-to-use-git-repositories/
